export const HOME_PAGE_ROUTE = '/home'
export const SIGN_IN_ROUTE = '/'
export const SIGN_UP_ROUTE = '/signup'
export const BOARDS_ROUTE = '/boards'
export const ACTIVITY_ROUTE = '/activity'
export const PROFILE_SETTIGNS = '/profile'